### ISSUE TITLE
Pas de connexion à la DB lors de l'upload de fichiers

### ISSUE THREAD

**Issue by clemorphy** [FileZ/FileZ#106]
Bonjour,

j'utilise la DB pour l'identification des utilisateurs.
L'étape du login fonctionne parfaitement, le lien avec la DB doit donc fonctionner.
Mais lors de l'upload d'un fichier, à la fin du transfert, le message suivant s'affiche :
"Une erreur inconnue est survenue pendant l'envoi du fichier."
En regardant filez-error.log, j'ai l'erreur suivante :
exception 'Exception' with message 'Unexisting database connection' in /home/monuser/domains/sous-domaine.mondomaine.net/public_html/lib/Fz/Db.php:139

Une idée ?
Pourquoi le lien avec la DB ne fonctionnerait plus lors de l'upload alors qu'il était fonctionnel pour le login ?
Pour info, le fichier uploadé ne se retrouve pas dans le répertoire des uploads, qui reste désespérément vide ...

Toute piste me serait grandement utile.
Merci.

**Comment by ianbogda** [comment]
Bonjour,

Pouvez vous mettre le contenu de votre filez.ini (sans les login / mot de passé d'accès à la base et autres information sensibles) ?

Autre point le répertoire upload est-il accessible par Apache ou ngnix?

**Comment by clemorphy** [comment]
Le répertoire upload est bien accessible par Apache.
PHP tourne en tant que module Apache, car en FCGId Filez m'indique que mod_rewrite ne fonctionne pas ...

Voici mon filez.ini :

```
[app]
debug = 1
use_url_rewriting = 1
log_dir = "/home/undomaine/domains/share.undomaine.net/logs"
upload_dir = "/home/undomaine/domains/share.undomaine.net/public_html/upload"
max_file_lifetime = 20
default_file_lifetime = 10
max_extend_count = 7
min_hash_size = 4
max_hash_size = 8
default_locale = "fr"
auth_handler_class = "Fz_Controller_Security_Internal"
user_factory_class = "Fz_User_Factory_Database"
user_quota = "2G"
https = "off"
sharing_destinations[] = "email"
admin_email = "clement@undomaine.net"

[db]
dsn = "mysql:host=localhost;dbname=share"
user = "notification@share.undomaine.net"
password = "unpassword"

[cron]
days_before_expiration_mail = 2
frequency = "+1 day"

[email]
from_name = "Share Notif"
from_email = "notification@share.undomaine.net"
host = "mail.share.undomaine.net"
name = "filez"
auth = "login"
username = "notification@share.undomaine.net"
password = "unpassword"

[user_factory_options]
db_use_global_conf = 1
db_table = "fz_user"
db_username_field = "username"
db_password_field = "password"
db_password_algorithm = "SHA1"

[user_attributes_translation]
firstname = "firstname"
lastname = "lastname"
email = "email"
id = "username"

[looknfeel]
show_credit = 1
help_url = "help"
```

EDIT :
Et pour info, voici tout le contenu de filez-error.log :

```
[2012-07-02 17:15:50] [123.123.123.123]   exception 'Exception' with message 'Unexisting database connection' in /home/undomaine/domains/share.undomaine.net/public_html/lib/Fz/Db.php:139
   Stack trace:
   #0 /home/undomaine/domains/share.undomaine.net/public_html/app/models/DbTable/Info.php(65): Fz_Db::getConnection()
   #1 /home/undomaine/domains/share.undomaine.net/public_html/app/models/DbTable/Info.php(94): App_Model_DbTable_Info->get('cron_freq')
   #2 /home/undomaine/domains/share.undomaine.net/public_html/lib/fz_helper_view.php(123): App_Model_DbTable_Info->getLastCronTimestamp()
   #3 /home/undomaine/domains/share.undomaine.net/public_html/app/views/layout/_footer.php(30): check_cron()
   #4 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(1410): include('/home/user...')
   #5 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(1435): render('layout/_footer....', NULL, Array)
   #6 /home/undomaine/domains/share.undomaine.net/public_html/app/views/layout/error.html.php(30): partial('layout/_footer....', Array)
   #7 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(1410): include('/home/user...')
   #8 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(1421): render('layout/error.ht...', NULL, Array)
   #9 [internal function]: render('Page not fo...', 'layout/error.ht...')
   #10 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(1450): call_user_func_array('render', Array)
   #11 /home/undomaine/domains/share.undomaine.net/public_html/lib/fz_limonade.php(73): html('Page not fo...', 'layout/error.ht...')
   #12 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(704): not_found(404, '(GET) /images/p...', '/home/user...', 376)
   #13 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(673): error_not_found_output(404, '(GET) /images/p...', '/home/user...', 376)
   #14 [internal function]: error_default_handler(404, '(GET) /images/p...', '/home/user...', 376)
   #15 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(1808): call_user_func_array('error_default_h...', Array)
   #16 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(647): call_if_exists('error_default_h...', 404, '(GET) /images/p...', '/home/user...', 376)
   #17 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(594): error_handler_dispatcher(404, '(GET) /images/p...', NULL, NULL)
   #18 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(376): halt(404, '(GET) /images/p...')
   #19 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(417): route_missing('GET', '/images/progres...')
   #20 /home/undomaine/domains/share.undomaine.net/public_html/index.php(222): run()
   #21 {main}
```

**Comment by clemorphy** [comment]
Du nouveau !

J'ai réussi à cerner la source du problème.
Le répertoire d'upload était à la racine de l'application, et s'appelait "upload", ce qui semble poser problème à Filez.
J'ai juste renommé ce répertoire "uploads" (avec un s), et là l'upload fonctionne bien.

Cependant, l'erreur citée ci-dessus est toujours présente dans le fichier de log lors d'un upload.
La progression d'upload ne fonctionne pas, je ne sais pas si ce message peut être lié à cela.
Pourtant un phpinfo m'indique que APC est bien installé avec "APC_UPLOAD_PROGRESS".

Du coup je ne sais vraiment pas à quoi correspond cette erreur dans le fichier de log, qui apparait à chaque upload.

**Comment by ianbogda** [comment]
Bonjour,

je n'ai pas encore trouvé le point concernant : `upload vs uploadS`

Si je prends les dernières traces du log que vous avez joint, nous avons :

```
#19 /home/undomaine/domains/share.undomaine.net/public_html/lib/limonade.php(417): route_missing('GET', '/images/progres...')
```

Est-ce qu'apache est propriétaire des répertoires comme `resources/images` ?

cdlt.

**Comment by ianbogda** [comment]
Bonjour,

quelle version de FileZ utilisez vous ? la branche `master` si oui à quelle date ? sinon quelle branche ?

Afin que j'installe la même version que vous pour les tests.

Cordialement
