### ISSUE TITLE
Erreur d'upload de fichier avec PHP7

### ISSUE THREAD

**Issue by Dam02738** [FileZ/FileZ#222]
Bonjour,
Est-ce que quelqu'un aurait testé filez avec php 7 sous ubuntu 16.04 ? 
Sous Php 5.5 pas de soucis mais sous PHP 7 impossible d'uploader un fichier.
Dans les logs il y aurait un soucis avec le format de date.

Merci d'avance.

**Comment by miha237** [comment]
Bonjour,
Tu pourrais nous fournir les logs de filez et un screenshot de l'erreur retournée via le navigateur ?

**Comment by TomKesteleyn** [comment]
Bonjour,

Is there already a solution for this issue. I've the same problem.

Kind regards

Tom Kesteleyn

**Comment by ych-bcs** [comment]
Bonjour,

J'ai un problème avec l'upload de fichier sur FileZ.

**Configuration :** 
Ubuntu : 16.04 LTS (Linux bcs-echange 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)
PHP : php7.0(amd64) 7.0.8-0ubuntu0.16.04.3

Message d'erreur lors de l'upload : 
[Mon Nov 14 11:54:29.200111 2016] [:error] [pid 3486] [client 2a01:6940:cafe:3000:95e3:5f0f:f690:9eb4:33624] PHP Notice:  Undefined offset: 8192 in /var/www/filez/htdocs/lib/fz_limonade.php on line 51, referer: https://dl.xxxx.com/

[Mon Nov 14 11:54:29.201172 2016] [:error] [pid 3486] [client 2a01:6940:cafe:3000:95e3:5f0f:f690:9eb4:33624] PHP Notice:  Undefined offset: 8192 in /var/www/filez/htdocs/lib/fz_limonade.php on line 51, referer: https://dl.xxxx.com/

[Mon Nov 14 11:54:29.202123 2016] [:error] [pid 3486] [client 2a01:6940:cafe:3000:95e3:5f0f:f690:9eb4:33624] PHP Notice:  Undefined index: use-password in /var/www/filez/htdocs/app/controllers/Upload.php on line 188, referer: https://dl.xxxx.com/

[Mon Nov 14 11:54:29.285171 2016] [:error] [pid 3486] [client 2a01:6940:cafe:3000:95e3:5f0f:f690:9eb4:33624] PHP Fatal error:  Uncaught Exception: Unexisting database connection in /var/www/filez/htdocs/lib/Fz/Db.php:139\nStack trace:\n#0 /var/www/filez/htdocs/app/models/DbTable/Info.php(65): Fz_Db::getConnection()\n#1 /var/www/filez/htdocs/app/models/DbTable/Info.php(94): App_Model_DbTable_Info->get('cron_freq')\n#2 /var/www/filez/htdocs/lib/fz_helper_view.php(123): App_Model_DbTable_Info->getLastCronTimestamp()\n#3 /var/www/filez/htdocs/app/views/layout/_footer.php(30): check_cron()\n#4 /var/www/filez/htdocs/lib/limonade.php(1410): include('/var/www/filez/...')\n#5 /var/www/filez/htdocs/lib/limonade.php(1435): render('layout/_footer....', NULL, Array)\n#6 /var/www/filez/htdocs/app/views/layout/error.html.php(30): partial('layout/_footer....', Array)\n#7 /var/www/filez/htdocs/lib/limonade.php(1410): include('/var/www/filez/...')\n#8 /var/www/filez/htdocs/lib/limonade.php(1421): render('layout/error.ht...', NULL, Array)\n#9 /var/www/filez/htdocs/lib/limonade.php(1450): render('  <h1>Internal ...', 'layout/error.ht...', Array)\n#10 /var/www/filez in /var/www/filez/htdocs/lib/Fz/Db.php on line 139, referer: https://dl.xxxx.com/


Merci.

Cordialement,

Yohan Chandler

**Comment by ych-bcs** [comment]
Bonjour,

Image du navigateur que vous pouvez voir ci-dessous :

![filez](https://cloud.githubusercontent.com/assets/23451358/20301047/19305f56-ab22-11e6-963b-9f1fe0c9b3e1.png)

Merci.

Cordialement,
Yohan Chandler.

**Comment by yverry** [comment]
Ton problème se situe plutôt sur #226
