### ISSUE TITLE
'Unknown date format' - Zend Exception

### ISSUE THREAD

**Issue by flather** [FileZ/FileZ#40]
Hi!
FileZ is awesome. I've tested it on my testing environment without having any issues.
But after installing FileZ on another server i'm getting an exception from Zend:

```
exception 'Zend_Locale_Exception' with message 'Unknown date format, neither date nor time in 'dd.MM.yy' found' in /web/filez/lib/Zend/Locale/Format.php:853
Stack trace:
#0 /web/filez/lib/Zend/Locale/Format.php(1122): Zend_Locale_Format::_parseDate('31.03.11', Array)
#1 /web/filez/lib/Zend/Date.php(2234): Zend_Locale_Format::getDate('31.03.11', Array)
#2 /web/filez/lib/Zend/Date.php(1078): Zend_Date->_calculate('set', '31.03.11', 'FF', 'de_DE')
#3 /web/filez/lib/Zend/Date.php(197): Zend_Date->set('31.03.11', 'FF', 'de_DE')
#4 /web/filez/app/controllers/Upload.php(111): Zend_Date->__construct('31.03.11', 'FF')
#5 /web/filez/app/controllers/Upload.php(50): App_Controller_Upload->saveFile(Array, Array)
#6 [internal function]: App_Controller_Upload->startAction()
#7 /web/filez/lib/fz_limonade.php(40): call_user_func(Array)
#8 [internal function]: fz_dispatcher('Upload', 'start')
#9 /web/filez/lib/limonade.php(411): call_user_func_array('fz_dispatcher', Array)
#10 /web/filez/index.php(184): run()
#11 {main}
```

iconv_get_encoding('internal_encoding') returns "ISO-8859-1"

It would be great if you could give me some advice.

**Comment by flather** [comment]
Due to some problems with iconv on our solaris server, iconv is not installed. This is why iconv_strpos doesn't return anything and Zend can't parse the date correctly.

I'm going to install FileZ on another linux server that has iconv installed.
