### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by sboulier** [FileZ/FileZ#59]
Bonjour,

cela fait plusieurs fois que je tente d'installer filez, mais impossible d'aller jusqu'au bout.
Le telechargement se passe bien, les droits sur les différents dossiers sont bons, mais impossible de passer la première page d'installation, la page suivante n'existe pas. "The requested URL /filez/configure was not found on this server"

D'où peut venir le problème?

merci d'avance.

**Comment by ArnaudD** [comment]
Bonjour,

Tout est là https://github.com/UAPV/FileZ/wiki/FAQ

**Comment by sboulier** [comment]
Oui, mais ... non j'ai vérifié cette partie avant de poster.

le htacces est bien présent et le contenu est bon, le mod rewrite est bien activé, et il y a bien "AllowOverride All" pour le virtualhost

J'ai également activé le mode debug, mais je n'ai rien dans le fichier de log.

Je suis sur une ubuntu 10.04, et j'ai installé tous les prérequis, une idée? :p

**Comment by ArnaudD** [comment]
Avez vous essayé de décommenté et modifié le paramètre RewriteBase dans le .htaccess ?

**Comment by sboulier** [comment]
Oui, j'ai repris l'installation du début sur une debian 6 pour voir, mais toujours le même problème, même lorsque je decommente le paramètre rewritebase et met le chemin complet. Je me demande si je n'ai pas simplement un problème de vhosts... ><

**Comment by isAAAc** [comment]
exactement le même problème que sboulier, 
j'ai suivi ce tuto http://pegasus45.free.fr/index.php?title=Ubuntu_10.04:_Installation_de_FileZ_2.0.2

tenté sur la dernière debian et la dernière ubuntu.

**Comment by ianbogda** [comment]
Bonjour,

Est-ce que les pistes évoquées dans la partie **404 error during installation : "The requested URL /configure was not found on this server."**  de https://github.com/FileZ/FileZ/wiki/FAQ résolvent votre problème ?

Sinon est-ce qu'apache est bien propriétaire de l'ensemble des dossiers, sous-dossiers et autres fichiers ?
`$ chown -R monsuser:mongroupe dossier`
Cdlt.

**Comment by aeki** [comment]
Bonjour,

Je rencontre le même problème d'installation. Je serai preneur d'avis d'initié.

Cordialement,

**Comment by Fredblue** [comment]
J'ai installé FileZ sur une Ubuntu 10.04 sans problème. #Ajout par Fred

dans mon /etc/apache2/conf.d/filez.conf conformément à la doc et à la FAQ
<IfModule mod_php5.c>
    php_admin_value upload_max_filesize 750M
    php_admin_value post_max_size 750M
    php_admin_value max_execution_time 1200
#php_admin_value upload_tmp_dir "/media/data/tmp"
</IfModule>

<Directory /var/www/filez>
Options FollowSymLinks
AllowOverride All
</Directory>

Le mod_rewrite est actif
fred@proxy:~$ grep -r rewrite /etc/apache2/mods-enabled/
/etc/apache2/mods-enabled/rewrite.load:LoadModule rewrite_module /usr/lib/apache2/modules/mod_rewrite.so

Mon .htaccess à la racine du répertoire de filez dans /var/www
<IfModule mod_rewrite.c>
  Options +FollowSymlinks
  Options +Indexes
  RewriteEngine on

  # RewriteBase /my_app/ # if your app is in a subfolder
  # RewriteBase /web/

  RewriteCond %{REQUEST_URI} !favicon.ico
  RewriteCond %{REQUEST_URI} !doc/user/(._).
  RewriteCond %{REQUEST_URI} !resources/(._).
  RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>

<IfModule mod_php5.c>
  php_value file_uploads On
  php_value upload_max_filesize 700M
  php_value post_max_size       700M
  php_value max_input_time      1200
  php_value max_execution_time  1200
</IfModule>

Les droits sur /var/www/filez
www-data www-data donc, il faut un chmod -R www-data:www-data /var/www/filez (machine de test sur le LAN)

Euh, avez-vous pensé à modifier config/filez.ini en fonction du répertoire de filez ?

**Comment by aeki** [comment]
Merci de votre réponse. Je suis sur Ubuntu 12.04 et pas sur 10.04

Rien n'y fait, j'ai bien vérifié ce que vous indiquez, mais impossible de charger la page de configuration de fileZ. 

Le fichier error.log de apache indique

[Mon Jun 10 17:59:39 2013] [error] [client 127.0.0.1] PHP Warning:  parse_ini_file(/var/www/filez/config/filez.ini): failed to open stream: No such file or directory in /var/www/filez/lib/fz_config.php on line 19, referer: http://127.0.0.1/filez/
[Mon Jun 10 17:59:39 2013] [error] [client 127.0.0.1] PHP Warning:  Missing or malformed config file. in /var/www/filez/lib/fz_config.php on line 23, referer: http://127.0.0.1/filez/
[Mon Jun 10 17:59:42 2013] [error] [client 127.0.0.1] File does not exist: /var/www/filez/configure, referer: http://127.0.0.1/filez/

J'ai effectivement pensé à créer directement un fichier config/filez.ini. Ci-dessous ma tentative:

-------- DEBUT FICHIER ---------------------------------
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; General configuration
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[app]
use_url_rewriting = true

; Must be writtable by the web server
upload_dir = /var/fz_uploads

; Must be writtable by the web server
log_dir = /var/log

; Allow downloading file sent with filez 1.x
filez1_compat = true

; Max and default lifetime of a file on the server
max_file_lifetime     = 20 
default_file_lifetime = 10

; Maximum number of days the lifetime of a file can be extended
max_extend_count = 7

; Min/Max size of files hash codes
min_hash_size = 4
max_hash_size = 6

; Default langage when no translation exists for the user locale
default_locale = fr

; Name of the class used to authenticate the user. Built-in handler are :
;  \* Fz_Controller_Security_Cas       Log the user against a CAS server
;  \* Fz_Controller_Security_Internal  Log the user with a built-in Controller.
;                                     This controller will check user/pass with
;                                     'login' method in the user factory.
auth_handler_class = Fz_Controller_Security_Internal

; Name of the class used to identify the user. Built-in factories are :
;  \* Fz_User_Factory_Ldap
;  \* Fz_User_Factory_Database
user_factory_class = Fz_User_Factory_Ldap

; Max disk spaced per user. Support shorthand format : M (Mega), G (Giga)
user_quota = 2G

; File extension allowed to be uploaded. Empty means no restriction
allowed_extensions = png,jpg,jpeg,gif

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Cron Job
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[cron]
; Number of days before before sending the notification mail for deletion
days_before_expiration_mail = 2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Look'n feel
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[looknfeel]
; Logo image
your_logo               = "resources/images/uapv-logo.gif"

; Custom CSS
; custom_css              = "resources/css/custom.css"

; show filez credits at the bottom of the pages
show_credit = true

; Url where the user will find Filez documentation
help_url = help ; Relative or absolute

; Where does the user reports bug ?
bug_report_href = mailto:some-one@somewhere.com ; or http://your-bug-tracker.com

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Database configuration
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[db]
dsn      = "mysql:host=localhost;dbname=filez"
user     = root
password = monMotDePasse

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Mail configuration
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[email]
from_email=monMail@monDomaine.fr  
from_name=Filez
host=smtp.monDomaine.fr
auth=login ; possible values = crammd5, login, plain
port=65
username=monCompte
password=monMotDePasse

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authentication configuration
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[auth_options]
; Parameters for the CAS authentication handler.
;cas_server_host = cas.univ-avignon.fr

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Identification configuration
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[user_factory_options]
; Parameters passed to the Ldap user factory.
; Available parameters : http://framework.zend.com/manual/en/zend.ldap.api.html
;host = ldap.univ-avignon.fr
;useSsl = false
;baseDn = "ou=people,dc=univ-avignon,dc=fr"
;bindRequiresDn = true

; Parameters for the Database user factory
db_use_global_conf    = true
db_server_dsn         = "mysql:host=localhost;dbname=filez"
db_server_user        = root
db_server_password    = monMotDePasse
db_table              = db_users
db_password_field     = password
db_username_field     = login
db_password_algorithm = MD5
; Possible algorithm are :
;   - MD5         (unsecure)
;   - SHA1        (unsecure)
;   - PHP Function name ex: "methodName"
;   - PHP Static method ex: "ClassName::Method"
;   - Plain SQL ex: "SHA1(CONCAT(salt, :password))"
;
; You have the possibility to block certain users with: (see also https://github.com/FileZ/FileZ/issues/12)
; accountFilterFormat   = "(&(objectClass=posixAccount)(uid=%s)(mailenable=true))"

[user_attributes_translation]
; In order to make the application schema agnostic with differents user storage
; facilities, each user attributes is translated from its original name to the
; application name. The syntax is as follow : application_name = original_name.
; This attributes are required by filez :
;  \* firstname
;  \* lastname
;  \* email
;  \* id
; Exemple for an Ldap repository :
firstname = givenname
lastname  = sn
email     = mail
id        = uid
-------- FIN FICHIER ---------------------------------

Mais pas mieux, je tombe sur une  "Internal Server Error : Unexisting database connection"

Pourtant j'ai bien créée la base 'filez' et la table 'db_users' via mysql

---

create database filez;
use filez;
CREATE TABLE `filez`.`db_users` (
 `uid` SERIAL NOT NULL ,
 `login` VARCHAR( 20 ) NOT NULL ,
 `password` VARCHAR( 40 ) NOT NULL ,
 `givenname` VARCHAR( 255 ) NOT NULL ,
 `sn` VARCHAR( 255 ) NOT NULL ,
 `mail` VARCHAR( 255 ) NOT NULL
) ENGINE = MYISAM ;

INSERT INTO `filez`.`db_users` 
 (`uid`, `login`, `password`, `givenname`, `sn`, `mail`) 

##  VALUES (NULL, 'admin', MD5('admin'), 'Admin', 'Olympe', 'admin@olympe.local');

Le fichier error.log de apache indique cette fois-ci

[Mon Jun 10 18:13:25 2013] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unexisting database connection' in /var/www/filez/lib/Fz/Db.php:139\nStack trace:\n#0 /var/www/filez/app/models/DbTable/Info.php(65): Fz_Db::getConnection()\n#1 /var/www/filez/app/models/DbTable/Info.php(94): App_Model_DbTable_Info->get('cron_freq')\n#2 /var/www/filez/lib/fz_helper_view.php(123): App_Model_DbTable_Info->getLastCronTimestamp()\n#3 /var/www/filez/app/views/layout/_footer.php(30): check_cron()\n#4 /var/www/filez/lib/limonade.php(1410): include('/var/www/filez/...')\n#5 /var/www/filez/lib/limonade.php(1435): render('layout/_footer....', NULL, Array)\n#6 /var/www/filez/app/views/layout/error.html.php(30): partial('layout/_footer....', Array)\n#7 /var/www/filez/lib/limonade.php(1410): include('/var/www/filez/...')\n#8 /var/www/filez/lib/limonade.php(1421): render('layout/error.ht...', NULL, Array)\n#9 [internal function]: render('  <h1>Internal ...', 'layout/error.ht...', Array)\n#10 /var/www/filez/lib/limonade.php(1450): call_user_func_array('render', Array)\n#11 /v in /var/www/filez/lib/Fz/Db.php on line 139

Y aurait-il des droits à régler pour l'accès à la base 'filez' ??

**Comment by soumdematte** [comment]
Bonjour,

J'arrive après la bataille mais pour info j'ai eu exactement le même souci avec ubuntu 12.04, j'ai mis le répertoire /var/www/filez en 777 et c'est passé.... jusqu'à ce que je sois bloqué car il manque le fichier login....

**Comment by Mickael-Martin** [comment]
Ce n'est pas un fonctionnement normal de mettre 777 sur ce dossier. Repars d'une installation propre et modifie ton fichier de conf petit à petit pour voir où ça bloque.

**Comment by soumdematte** [comment]
Ça y est j'ai remis les droits de base mais je ne peux toujours pas ouvrir la page login.php après avoir lancé la configuration

**Comment by Mickael-Martin** [comment]
quel est le propriétaire de tes dossiers/fichiers filez ?

**Comment by ianbogda** [comment]
try the last FileZ (7c0ac48dcd0ae5cb3a5a86d87e1e85b3ba1eaa50)

**Comment by ianbogda** [comment]
Avez-vou essayer avec [la dernière version](https://github.com/FileZ/FileZ/archive/master.zip) qui est fonctionnelle ?

**Comment by soumdematte** [comment]
j'ai répondu x fois, mon commentaire apparait puis disparait après quelques heures....

du coup je recommence :  tout fonctionne correctement !
