### ISSUE TITLE
emailing file does not work

### ISSUE THREAD

**Issue by papangue** [FileZ/FileZ#80]
Hi everybody
The soft is very interesting, and i want to deploy it in my structure. But i have a big problem:

Fresh installation
on Fedore core 15

when i send the file by email i receive a message "Page not found"

in the log i have

[2012-02-16 15:31:58] [192.168.5.254]   exception 'Exception' with message 'Unexisting database connection' in /var/www/html/filez/lib/Fz/Db.php:137
   Stack trace:
   #0 /var/www/html/filez/app/models/DbTable/Info.php(65): Fz_Db::getConnection()
   #1 /var/www/html/filez/app/models/DbTable/Info.php(94): App_Model_DbTable_Info->get('cron_freq')
   #2 /var/www/html/filez/lib/fz_helper_view.php(123): App_Model_DbTable_Info->getLastCronTimestamp()
   #3 /var/www/html/filez/app/views/layout/_footer.php(30): check_cron()
   #4 /var/www/html/filez/lib/limonade.php(1410): include('/var/www/html/f...')
   #5 /var/www/html/filez/lib/limonade.php(1435): render('layout/_footer....', NULL, Array)
   #6 /var/www/html/filez/app/views/layout/error.html.php(30): partial('layout/_footer....', Array)
   #7 /var/www/html/filez/lib/limonade.php(1410): include('/var/www/html/f...')
   #8 /var/www/html/filez/lib/limonade.php(1421): render('layout/error.ht...', NULL, Array)
   #9 [internal function]: render('Page not fo...', 'layout/error.ht...')
   #10 /var/www/html/filez/lib/limonade.php(1450): call_user_func_array('render', Array)
   #11 /var/www/html/filez/lib/fz_limonade.php(73): html('
Page not fo...', 'layout/error.ht...')
   #12 /var/www/html/filez/lib/limonade.php(704): not_found(404, '(POST) /', '/var/www/html/f...', 376)
   #13 /var/www/html/filez/lib/limonade.php(673): error_not_found_output(404, '(POST) /', '/var/www/html/f...', 376)
   #14 [internal function]: error_default_handler(404, '(POST) /', '/var/www/html/f...', 376)
   #15 /var/www/html/filez/lib/limonade.php(1808): call_user_func_array('error_default_h...', Array)
   #16 /var/www/html/filez/lib/limonade.php(647): call_if_exists('error_default_h...', 404, '(POST) /', '/var/www/html/f...', 376)
   #17 /var/www/html/filez/lib/limonade.php(594): error_handler_dispatcher(404, '(POST) /', NULL, NULL)
   #18 /var/www/html/filez/lib/limonade.php(376): halt(404, '(POST) /')
   #19 /var/www/html/filez/lib/limonade.php(417): route_missing('POST', '/')
   #20 /var/www/html/filez/index.php(235): run()
   #21 {main}

I have applied the fix https://gist.github.com/977366 in accordance to https://github.com/FileZ/FileZ/issues/58

could you help me please?
Thanx

**Comment by papangue** [comment]
sorry - the fix has succeeded in correcting the bug

yep - could you include  it the source?

thanx

**Comment by papangue** [comment]
bye
